function makeHoldToken(){if(crypto.randomUUID)return crypto.randomUUID();const a=new Uint8Array(32);crypto.getRandomValues(a);return Array.from(a,b=>b.toString(16).padStart(2,"0")).join("")}
const state={routes:[],trips:[],selectedTrip:null,selectedSeat:null,seatStatus:new Map(),holdToken:makeHoldToken(),holdExpiresAt:null,seatPoller:null,refreshingSeats:false,holdBusy:false,holdTimer:null};

const $=id=>document.getElementById(id);
const rupiah=n=>new Intl.NumberFormat("id-ID",{style:"currency",currency:"IDR",maximumFractionDigits:0}).format(n||0);
const api=(table,params="")=>fetch(`${SUPABASE_URL}/rest/v1/${table}${params}`,{headers:{apikey:SUPABASE_PUBLISHABLE_KEY,Authorization:`Bearer ${SUPABASE_PUBLISHABLE_KEY}`}}).then(async r=>{if(!r.ok)throw new Error(await r.text());return r.json()});
function rpc(name,body){return fetch(`${SUPABASE_URL}/rest/v1/rpc/${name}`,{method:"POST",headers:{apikey:SUPABASE_PUBLISHABLE_KEY,Authorization:`Bearer ${SUPABASE_PUBLISHABLE_KEY}`,"Content-Type":"application/json"},body:JSON.stringify(body)}).then(async r=>{if(!r.ok)throw new Error(await r.text());return r.json()})}

async function init(){
  const now=new Date();
  const localDate=new Date(now.getTime()-now.getTimezoneOffset()*60000).toISOString().slice(0,10);
  $("travelDate").value=localDate;
  try{state.routes=await api("routes","?select=*&active=eq.true&order=origin,destination");fillRouteOptions();$("searchMessage").textContent="Database terhubung."}
  catch(e){$("searchMessage").textContent="Gagal menghubungkan database: "+friendlyError(e)}
}
function fillRouteOptions(){const origins=[...new Set(state.routes.map(r=>r.origin))],destinations=[...new Set(state.routes.map(r=>r.destination))];$("origin").innerHTML='<option value="">Pilih kota asal</option>'+origins.map(x=>`<option>${esc(x)}</option>`).join("");$("destination").innerHTML='<option value="">Pilih kota tujuan</option>'+destinations.map(x=>`<option>${esc(x)}</option>`).join("")}
async function searchTrips(){stopSeatPolling();await releaseOwnHold(false);clearHoldTimer();state.selectedTrip=null;state.selectedSeat=null;state.holdExpiresAt=null;state.seatStatus.clear();const o=$("origin").value,d=$("destination").value,date=$("travelDate").value;if(!o||!d||!date){$("searchMessage").textContent="Lengkapi asal, tujuan, dan tanggal.";return}const route=state.routes.find(r=>r.origin===o&&r.destination===d);if(!route){$("searchMessage").textContent="Rute belum tersedia.";return}try{state.trips=await api("schedules",`?select=id,departure_date,departure_time,route_id,bus_id,active,routes!inner(origin,destination,price),buses!inner(bus_name,bus_number,bus_class,capacity,vehicle_type,layout_type)&route_id=eq.${route.id}&departure_date=eq.${date}&active=eq.true&order=departure_time`);renderTrips()}catch(e){$("searchMessage").textContent="Gagal mengambil jadwal: "+friendlyError(e)}}
function renderTrips(){$("resultsSection").classList.remove("hidden");$("resultCount").textContent=`${state.trips.length} perjalanan`;if(!state.trips.length){$("results").innerHTML='<p class="message">Belum ada jadwal untuk tanggal tersebut.</p>';return}$("results").innerHTML=state.trips.map(t=>`<div class="trip"><div class="trip-main"><strong>${esc(t.departure_time.slice(0,5))} WIB</strong><div class="trip-meta">${esc(t.buses.bus_name)} • ${esc(t.buses.bus_number)} • ${esc(t.buses.bus_class)}</div></div><div class="trip-price">${rupiah(t.routes.price)}<br><small>${Number(t.buses.capacity)||0} kursi</small></div><button class="primary" onclick="chooseTrip('${t.id}')">Pilih Perjalanan</button></div>`).join("")}

async function loadSeatStatus(scheduleId,{silent=false}={}){
  if(state.refreshingSeats)return;state.refreshingSeats=true;
  try{
    const rows=await rpc("get_seat_status",{p_schedule_id:scheduleId});
    state.seatStatus=new Map((rows||[]).map(x=>[Number(x.seat_number),String(x.seat_state)]));
    const ownSeat=state.selectedSeat;
    if(ownSeat!==null && state.seatStatus.get(ownSeat)==="booked"){
      await releaseOwnHold(false);state.selectedSeat=null;state.holdExpiresAt=null;clearHoldTimer();$("selectedSeatText").textContent="-";$("bookBtn").disabled=true;$("bookingMessage").textContent="Kursi yang Anda pilih baru saja dipesan penumpang lain. Silakan pilih kursi lain.";
    }
    if(state.selectedTrip&&state.selectedTrip.id===scheduleId){renderSeats(state.selectedTrip.buses.layout_type,state.selectedTrip.buses.capacity);updateSeatCount()}
  }catch(e){if(!silent)$("bookingMessage").textContent="Gagal memuat status kursi: "+friendlyError(e)}finally{state.refreshingSeats=false}
}
function updateSeatCount(){if(!state.selectedTrip)return;const capacity=Number(state.selectedTrip.buses.capacity)||0;let booked=0,held=0;for(const [n,s] of state.seatStatus){if(n>=1&&n<=capacity){if(s==="booked")booked++;if(s==="held")held++}}const available=Math.max(capacity-booked-held,0);const el=$("seatAvailability");if(el)el.textContent=`${available} tersedia • ${booked} terisi • ${held} dikunci sementara`}
function startSeatPolling(){stopSeatPolling();if(!state.selectedTrip)return;state.seatPoller=setInterval(()=>{if(document.visibilityState==="visible"&&state.selectedTrip)loadSeatStatus(state.selectedTrip.id,{silent:true})},5000)}
function stopSeatPolling(){if(state.seatPoller){clearInterval(state.seatPoller);state.seatPoller=null}}

async function chooseTrip(id){stopSeatPolling();await releaseOwnHold(false);clearHoldTimer();state.selectedTrip=state.trips.find(t=>t.id===id);state.selectedSeat=null;state.holdExpiresAt=null;if(!state.selectedTrip)return;$("bookingSection").classList.remove("hidden");$("selectedTrip").textContent=`${state.selectedTrip.departure_time.slice(0,5)} WIB • ${state.selectedTrip.buses.bus_name} • ${state.selectedTrip.buses.vehicle_type||"Armada"}`;$("priceText").textContent=rupiah(state.selectedTrip.routes.price);$("selectedSeatText").textContent="-";$("bookBtn").disabled=true;$("bookingMessage").textContent="Memuat status kursi...";await loadSeatStatus(id);$("bookingMessage").textContent="Pilih kursi. Kursi akan dikunci sementara selama 10 menit.";startSeatPolling();$("bookingSection").scrollIntoView({behavior:"smooth"})}

function seatButton(n){const st=state.seatStatus.get(n)||"available";const own=state.selectedSeat===n;let label="TERSEDIA",cls="available",disabled="";if(st==="booked"){label="TERISI";cls="booked";disabled="disabled"}else if(st==="held"&&!own){label="DIKUNCI";cls="held";disabled="disabled"}else if(own){label="DIPILIH";cls="selected"}return `<button class="seat-btn" ${disabled} onclick="selectSeat(${n})" aria-label="Kursi P${n}" title="${label}"><span class="seat ${cls}"><b>P${n}</b><small>${label}</small></span></button>`}
function renderSeats(layoutType,capacity){if(layoutType==="hiace_10"){$("seatGrid").className="seat-grid hiace-layout";$("seatGrid").innerHTML=`<div class="vehicle-shell"><div class="vehicle-front"><span>DEPAN</span><small>KACA UTAMA</small></div><div class="front-row">${seatButton(1)}<div class="driver-seat"><b>DRIVER</b><small>Pengemudi</small></div></div><div class="door-label"><span>PINTU GESER</span></div><div class="passenger-row">${seatButton(4)}${seatButton(3)}${seatButton(2)}</div><div class="passenger-row">${seatButton(5)}${seatButton(6)}${seatButton(7)}</div><div class="passenger-row">${seatButton(8)}${seatButton(9)}${seatButton(10)}</div><div class="luggage">BAGASI PENYIMPANAN BELAKANG</div></div>`}else if(["bus_24","bus_30","bus_40","bus_45"].includes(layoutType)){$("seatGrid").className="seat-grid";const total=Number(capacity)||0;$("seatGrid").innerHTML=Array.from({length:total},(_,i)=>seatButton(i+1)).join("")}else{$("seatGrid").className="seat-grid";$("seatGrid").innerHTML='<p class="message">Layout kendaraan belum dikenali. Silakan hubungi admin.</p>'}updateSeatCount()}

async function selectSeat(n){if(!state.selectedTrip||state.holdBusy)return;const capacity=Number(state.selectedTrip.buses.capacity)||0;if(n<1||n>capacity)return;const current=state.seatStatus.get(n)||"available";if(current==="booked"||current==="held")return;
  state.holdBusy=true;$("bookingMessage").textContent="Mengunci kursi sementara...";try{
    if(state.selectedSeat!==null&&state.selectedSeat!==n)await releaseOwnHold(false);
    const data=await rpc("hold_seat",{p_schedule_id:state.selectedTrip.id,p_seat_number:n,p_hold_token:state.holdToken,p_hold_minutes:10});
    state.selectedSeat=n;state.holdExpiresAt=new Date(data.expires_at).getTime();$("selectedSeatText").textContent=`P${n}`;$("bookBtn").disabled=false;$("bookingMessage").textContent="Kursi berhasil dikunci sementara. Selesaikan booking sebelum waktu habis.";startHoldTimer();await loadSeatStatus(state.selectedTrip.id,{silent:true});
  }catch(e){$("bookingMessage").textContent="Kursi tidak dapat dikunci: "+friendlyError(e);await loadSeatStatus(state.selectedTrip.id,{silent:true})}finally{state.holdBusy=false}
}
async function releaseOwnHold(showMessage=true){if(!state.selectedTrip)return;try{await rpc("release_seat_hold",{p_schedule_id:state.selectedTrip.id,p_hold_token:state.holdToken})}catch(_){ }if(state.selectedSeat!==null){state.seatStatus.delete(state.selectedSeat);state.selectedSeat=null}state.holdExpiresAt=null;clearHoldTimer();if($("selectedSeatText"))$("selectedSeatText").textContent="-";if($("bookBtn"))$("bookBtn").disabled=true;if(showMessage)$("bookingMessage").textContent="Kunci sementara dilepas."}
function startHoldTimer(){clearHoldTimer();const tick=()=>{if(!state.holdExpiresAt){$("holdCountdown").textContent="";return}const left=Math.max(0,state.holdExpiresAt-Date.now());if(left<=0){clearHoldTimer();state.selectedSeat=null;state.holdExpiresAt=null;$("selectedSeatText").textContent="-";$("bookBtn").disabled=true;$("holdCountdown").textContent="Waktu habis";$("bookingMessage").textContent="Waktu kunci kursi habis. Silakan pilih kursi lagi.";if(state.selectedTrip)loadSeatStatus(state.selectedTrip.id,{silent:true});return}const sec=Math.ceil(left/1000),m=Math.floor(sec/60),s=String(sec%60).padStart(2,"0");$("holdCountdown").textContent=`Kunci kursi: ${m}:${s}`};tick();state.holdTimer=setInterval(tick,1000)}
function clearHoldTimer(){if(state.holdTimer){clearInterval(state.holdTimer);state.holdTimer=null}if($("holdCountdown"))$("holdCountdown").textContent=""}
function makeBookingCode(){const time=Date.now().toString().slice(-8),random=Math.floor(Math.random()*900+100);return `IKS-${time}${random}`.slice(0,12)}

async function createBooking(){const t=state.selectedTrip,name=$("passengerName").value.trim(),phone=$("passengerPhone").value.trim(),seat=state.selectedSeat;if(!t||!seat||!name||!phone){$("bookingMessage").textContent="Lengkapi kursi, nama, dan WhatsApp.";return}if(!state.holdExpiresAt||state.holdExpiresAt<=Date.now()){$("bookingMessage").textContent="Kunci kursi sudah habis. Silakan pilih kursi lagi.";await loadSeatStatus(t.id);return}const capacity=Number(t.buses.capacity)||0;if(seat<1||seat>capacity){$("bookingMessage").textContent="Nomor kursi tidak valid.";return}$("bookBtn").disabled=true;$("bookingMessage").textContent="Mengonfirmasi kunci kursi dan menyimpan booking...";const code=makeBookingCode();try{const data=await rpc("create_booking_v1_8",{p_booking_code:code,p_schedule_id:t.id,p_passenger_name:name,p_passenger_phone:phone,p_seat_number:seat,p_price:Number(t.routes.price)||0,p_hold_token:state.holdToken});const ticket={code:data?.booking_code||code,name:data?.passenger_name||name,phone,seat:Number(data?.seat_number||seat),trip:t};state.seatStatus.set(ticket.seat,"booked");state.selectedSeat=null;state.holdExpiresAt=null;clearHoldTimer();$("selectedSeatText").textContent="-";renderSeats(t.buses.layout_type,t.buses.capacity);$("bookingMessage").textContent="Booking berhasil. Kursi telah terisi.";showTicket(ticket)}catch(e){$("bookingMessage").textContent="Booking gagal: "+friendlyError(e);await loadSeatStatus(t.id,{silent:true});$("bookBtn").disabled=true}}
function showTicket(x){$("ticketCode").textContent=x.code;$("ticketName").textContent=x.name;$("ticketPhone").textContent=x.phone;$("ticketRoute").textContent=`${x.trip.routes.origin} → ${x.trip.routes.destination}`;$("ticketSchedule").textContent=`${x.trip.departure_date} • ${x.trip.departure_time.slice(0,5)} WIB`;$("ticketBus").textContent=`${x.trip.buses.bus_name} (${x.trip.buses.bus_number})`;$("ticketSeat").textContent=`P${x.seat}`;$("ticketPrice").textContent=rupiah(x.trip.routes.price);$("ticketSection").classList.remove("hidden");$("ticketSection").scrollIntoView({behavior:"smooth"})}
async function resetBooking(){stopSeatPolling();await releaseOwnHold(false);$("ticketSection").classList.add("hidden");$("bookingSection").classList.add("hidden");$("passengerName").value="";$("passengerPhone").value="";$("bookingMessage").textContent="";state.selectedTrip=null;state.selectedSeat=null;state.seatStatus.clear()}
function friendlyError(e){try{const raw=String(e.message||e),parsed=JSON.parse(raw);return parsed.message||raw}catch(_){return String(e.message||e).replace(/^Error:\s*/i,"")}}
function esc(s){return String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]))}

$("searchBtn").onclick=searchTrips;$("bookBtn").onclick=createBooking;$("newBookingBtn").onclick=resetBooking;
document.addEventListener("visibilitychange",()=>{if(document.visibilityState==="visible"&&state.selectedTrip)loadSeatStatus(state.selectedTrip.id,{silent:true})});
window.addEventListener("beforeunload",()=>{stopSeatPolling();clearHoldTimer()});
init();
